tcp:
  host: 0.0.0.0
  port: 5002
paths:
  outbox: /Users/thethian91/Documents/projects/integraciones/lab-integrator-v2/inbox
memo:
  limit: 200000
input:
  mode: tcp
file:
  inbox_dir: /Users/thethian91/Documents/projects/integraciones/lab-integrator-v2/inbox
logging:
  to_file: false
  level: INFO
api:
  base_url: https://demo.rednacional.com.co/erp/snt/websys_webservices.snt
  key: 22e88df2be4da512dbcbba4c7df1c7jf
  secret: ea9fe9f5f18506f1e5c1983986e0c82e
  action: ordenes_laboratorio_fecha
  use_mock: true
  mock_file: samples/orders_20250901.xml
orders:
  poll_every_sec: 0.0
monitor:
  autostart_server: true
results_export:
  enabled: true
  interval_ms: 5000
  batch_size: 200
  outbox: outbox_xml
